// Generated by Wrangler on Thu Jun 13 2024 15:08:37 GMT+0300 (Israel Daylight Time)
// by running `wrangler types`

interface Env {
	STORAGE: KVNamespace;
	BOT_INFO: string;
	ENVISO_API_KEY: string;
	TELEGRAM_BOT_TOKEN: string;
}
