#:schema node_modules/wrangler/config-schema.json
name = "afm-tickets-periodic"
main = "src/index.ts"
compatibility_date = "2024-06-10"

[triggers]
crons = ["0 * * * *"] # * * * * * = run every minute

[vars]
BOT_INFO = "{\"id\":7210640302,\"is_bot\":true,\"first_name\":\"Anne Frank Museum Tickets Bot\",\"username\":\"afm_tickets_bot\",\"can_join_groups\":true,\"can_read_all_group_messages\":false,\"supports_inline_queries\":false,\"can_connect_to_business\":false}"
ENVISO_API_KEY = "JOpTxzEfCEW/DRMhU7eTew=="

[[kv_namespaces]]
binding = "STORAGE"
id = "1123730b393d43fba0a28d46fcf2ce17"
